# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add.ui'
#
# Created: Thu Sep 24 01:32:06 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(700, 655)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(700, 600))
        mainWindow.setBaseSize(QtCore.QSize(3, 3))
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_seen = QtGui.QLabel(self.centralwidget)
        self.label_seen.setGeometry(QtCore.QRect(371, 320, 50, 30))
        self.label_seen.setObjectName("label_seen")
        self.slider_seen = QtGui.QSlider(self.centralwidget)
        self.slider_seen.setGeometry(QtCore.QRect(462, 320, 160, 29))
        self.slider_seen.setMaximum(100)
        self.slider_seen.setOrientation(QtCore.Qt.Horizontal)
        self.slider_seen.setObjectName("slider_seen")
        self.btn_add = QtGui.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(290, 550, 98, 27))
        self.btn_add.setObjectName("btn_add")
        self.seekSlider = phonon.Phonon.SeekSlider(self.centralwidget)
        self.seekSlider.setGeometry(QtCore.QRect(149, 260, 351, 29))
        self.seekSlider.setObjectName("seekSlider")
        self.btn_folder = QtGui.QPushButton(self.centralwidget)
        self.btn_folder.setGeometry(QtCore.QRect(540, 220, 100, 27))
        self.btn_folder.setObjectName("btn_folder")
        self.btn_nxt = QtGui.QPushButton(self.centralwidget)
        self.btn_nxt.setGeometry(QtCore.QRect(540, 250, 98, 27))
        self.btn_nxt.setObjectName("btn_nxt")
        self.btn_play = QtGui.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(30, 260, 98, 27))
        self.btn_play.setObjectName("btn_play")
        self.label_per = QtGui.QLabel(self.centralwidget)
        self.label_per.setGeometry(QtCore.QRect(430, 330, 16, 10))
        self.label_per.setObjectName("label_per")
        self.label_fileName = QtGui.QLabel(self.centralwidget)
        self.label_fileName.setGeometry(QtCore.QRect(40, 230, 66, 17))
        self.label_fileName.setObjectName("label_fileName")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 310, 300, 211))
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(167, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.combo_task = QtGui.QComboBox(self.widget)
        self.combo_task.setMinimumSize(QtCore.QSize(100, 0))
        self.combo_task.setEditable(False)
        self.combo_task.setObjectName("combo_task")
        self.gridLayout.addWidget(self.combo_task, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(167, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.combo_type = QtGui.QComboBox(self.widget)
        self.combo_type.setMinimumSize(QtCore.QSize(100, 0))
        self.combo_type.setObjectName("combo_type")
        self.gridLayout.addWidget(self.combo_type, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(167, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.combo_quality = QtGui.QComboBox(self.widget)
        self.combo_quality.setMinimumSize(QtCore.QSize(100, 0))
        self.combo_quality.setObjectName("combo_quality")
        self.gridLayout.addWidget(self.combo_quality, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setMaximumSize(QtCore.QSize(167, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.check_pass = QtGui.QCheckBox(self.widget)
        self.check_pass.setText("")
        self.check_pass.setObjectName("check_pass")
        self.gridLayout.addWidget(self.check_pass, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setMaximumSize(QtCore.QSize(167, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.combo_time = QtGui.QComboBox(self.widget)
        self.combo_time.setMinimumSize(QtCore.QSize(100, 0))
        self.combo_time.setObjectName("combo_time")
        self.gridLayout.addWidget(self.combo_time, 4, 1, 1, 1)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(371, 364, 260, 160))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtGui.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 2)
        self.check_false = QtGui.QCheckBox(self.widget1)
        self.check_false.setText("")
        self.check_false.setObjectName("check_false")
        self.gridLayout_2.addWidget(self.check_false, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.combo_location = QtGui.QComboBox(self.widget1)
        self.combo_location.setObjectName("combo_location")
        self.gridLayout_2.addWidget(self.combo_location, 1, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.combo_year = QtGui.QComboBox(self.widget1)
        self.combo_year.setMaxVisibleItems(7)
        self.combo_year.setObjectName("combo_year")
        self.gridLayout_2.addWidget(self.combo_year, 2, 1, 1, 2)
        self.label_10 = QtGui.QLabel(self.widget1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.line_tags = QtGui.QLineEdit(self.widget1)
        self.line_tags.setObjectName("line_tags")
        self.gridLayout_2.addWidget(self.line_tags, 3, 1, 1, 2)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 25))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.label_seen.setBuddy(self.slider_seen)
        self.label.setBuddy(self.combo_task)
        self.label_2.setBuddy(self.combo_type)
        self.label_3.setBuddy(self.combo_quality)
        self.label_4.setBuddy(self.check_pass)
        self.label_8.setBuddy(self.combo_time)
        self.label_6.setBuddy(self.check_false)
        self.label_9.setBuddy(self.combo_location)
        self.label_7.setBuddy(self.combo_year)
        self.label_10.setBuddy(self.line_tags)

        self.retranslateUi(mainWindow)
        self.combo_task.setCurrentIndex(-1)
        QtCore.QObject.connect(self.slider_seen, QtCore.SIGNAL("valueChanged(int)"), self.label_per.setNum)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.combo_task, self.combo_type)
        mainWindow.setTabOrder(self.combo_type, self.combo_quality)
        mainWindow.setTabOrder(self.combo_quality, self.check_pass)
        mainWindow.setTabOrder(self.check_pass, self.combo_time)
        mainWindow.setTabOrder(self.combo_time, self.slider_seen)
        mainWindow.setTabOrder(self.slider_seen, self.check_false)
        mainWindow.setTabOrder(self.check_false, self.combo_location)
        mainWindow.setTabOrder(self.combo_location, self.combo_year)
        mainWindow.setTabOrder(self.combo_year, self.line_tags)
        mainWindow.setTabOrder(self.line_tags, self.btn_add)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Add Video", None, QtGui.QApplication.UnicodeUTF8))
        self.label_seen.setText(QtGui.QApplication.translate("mainWindow", "% Seen", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add.setText(QtGui.QApplication.translate("mainWindow", "ADD", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_folder.setText(QtGui.QApplication.translate("mainWindow", "Select folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_nxt.setText(QtGui.QApplication.translate("mainWindow", "next >>", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_play.setText(QtGui.QApplication.translate("mainWindow", "Play >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_per.setText(QtGui.QApplication.translate("mainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fileName.setText(QtGui.QApplication.translate("mainWindow", "file", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainWindow", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "Should pass", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mainWindow", "False Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("mainWindow", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mainWindow", "Year", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("mainWindow", "Other Tags", None, QtGui.QApplication.UnicodeUTF8))

from PySide import phonon
